# -*- coding: UTF-8 -*-
# editor: JiaYunSong
# Created by: PyQt5 UI code generator 5.15.0


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1301, 781)
        self.AttrUpdateOrDel_groupBox = QtWidgets.QGroupBox(Dialog)
        self.AttrUpdateOrDel_groupBox.setGeometry(QtCore.QRect(20, 30, 1251, 591))
        self.AttrUpdateOrDel_groupBox.setStyleSheet("border:1px solid black")
        self.AttrUpdateOrDel_groupBox.setObjectName("AttrUpdateOrDel_groupBox")
        self.InputAttrName_TextEdit = QtWidgets.QTextEdit(self.AttrUpdateOrDel_groupBox)
        self.InputAttrName_TextEdit.setGeometry(QtCore.QRect(20, 30, 1001, 31))
        self.InputAttrName_TextEdit.setObjectName("InputAttrName_TextEdit")
        self.AttrSearch_Button = QtWidgets.QPushButton(self.AttrUpdateOrDel_groupBox)
        self.AttrSearch_Button.setGeometry(QtCore.QRect(1050, 30, 181, 31))
        self.AttrSearch_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}")
        self.AttrSearch_Button.setObjectName("AttrSearch_Button")
        self.Attr_TableWidget = QtWidgets.QTableWidget(self.AttrUpdateOrDel_groupBox)
        self.Attr_TableWidget.setGeometry(QtCore.QRect(20, 80, 901, 491))
        self.Attr_TableWidget.setObjectName("Attr_TableWidget")
        self.Attr_TableWidget.setColumnCount(7)
        self.Attr_TableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.Attr_TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Attr_TableWidget.setItem(0, 4, item)
        self.AddName_plainTextEdit = QtWidgets.QPlainTextEdit(self.AttrUpdateOrDel_groupBox)
        self.AddName_plainTextEdit.setGeometry(QtCore.QRect(940, 80, 291, 41))
        self.AddName_plainTextEdit.setObjectName("AddName_plainTextEdit")
        self.AddX_plainTextEdit = QtWidgets.QPlainTextEdit(self.AttrUpdateOrDel_groupBox)
        self.AddX_plainTextEdit.setGeometry(QtCore.QRect(940, 130, 141, 31))
        self.AddX_plainTextEdit.setObjectName("AddX_plainTextEdit")
        self.AddY_plainTextEdit = QtWidgets.QPlainTextEdit(self.AttrUpdateOrDel_groupBox)
        self.AddY_plainTextEdit.setGeometry(QtCore.QRect(1090, 130, 141, 31))
        self.AddY_plainTextEdit.setObjectName("AddY_plainTextEdit")
        self.AddMiniIntro_plainTextEdit = QtWidgets.QPlainTextEdit(self.AttrUpdateOrDel_groupBox)
        self.AddMiniIntro_plainTextEdit.setGeometry(QtCore.QRect(940, 170, 291, 111))
        self.AddMiniIntro_plainTextEdit.setObjectName("AddMiniIntro_plainTextEdit")
        self.AddIntro_plainTextEdit = QtWidgets.QPlainTextEdit(self.AttrUpdateOrDel_groupBox)
        self.AddIntro_plainTextEdit.setGeometry(QtCore.QRect(940, 290, 291, 181))
        self.AddIntro_plainTextEdit.setObjectName("AddIntro_plainTextEdit")
        self.AddActive_plainTextEdit = QtWidgets.QPlainTextEdit(self.AttrUpdateOrDel_groupBox)
        self.AddActive_plainTextEdit.setGeometry(QtCore.QRect(940, 480, 291, 61))
        self.AddActive_plainTextEdit.setObjectName("AddActive_plainTextEdit")
        self.Add_Button = QtWidgets.QPushButton(self.AttrUpdateOrDel_groupBox)
        self.Add_Button.setGeometry(QtCore.QRect(940, 550, 91, 25))
        self.Add_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}")
        self.Add_Button.setObjectName("Add_Button")
        self.AttrUpdate_Button = QtWidgets.QPushButton(self.AttrUpdateOrDel_groupBox)
        self.AttrUpdate_Button.setGeometry(QtCore.QRect(1040, 550, 91, 25))
        self.AttrUpdate_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}")
        self.AttrUpdate_Button.setObjectName("AttrUpdate_Button")
        self.AttrDelete_Button = QtWidgets.QPushButton(self.AttrUpdateOrDel_groupBox)
        self.AttrDelete_Button.setGeometry(QtCore.QRect(1140, 550, 91, 25))
        self.AttrDelete_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}")
        self.AttrDelete_Button.setObjectName("AttrDelete_Button")
        self.PathUpdate_groupBox = QtWidgets.QGroupBox(Dialog)
        self.PathUpdate_groupBox.setGeometry(QtCore.QRect(20, 650, 1021, 111))
        self.PathUpdate_groupBox.setStyleSheet("border:1px solid black")
        self.PathUpdate_groupBox.setObjectName("PathUpdate_groupBox")
        self.Destination_TextEdit = QtWidgets.QPlainTextEdit(self.PathUpdate_groupBox)
        self.Destination_TextEdit.setGeometry(QtCore.QRect(330, 30, 271, 31))
        self.Destination_TextEdit.setObjectName("Destination_TextEdit")
        self.StartingPoint_TextEdit = QtWidgets.QPlainTextEdit(self.PathUpdate_groupBox)
        self.StartingPoint_TextEdit.setGeometry(QtCore.QRect(30, 30, 271, 31))
        self.StartingPoint_TextEdit.setObjectName("StartingPoint_TextEdit")
        self.PathSearch_Button = QtWidgets.QPushButton(self.PathUpdate_groupBox)
        self.PathSearch_Button.setGeometry(QtCore.QRect(490, 70, 131, 25))
        self.PathSearch_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}")
        self.PathSearch_Button.setObjectName("PathSearch_Button")
        self.To_Label = QtWidgets.QLabel(self.PathUpdate_groupBox)
        self.To_Label.setGeometry(QtCore.QRect(300, 30, 31, 31))
        self.To_Label.setStyleSheet("border-color: rgba(255, 255, 255, 0);")
        self.To_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.To_Label.setObjectName("To_Label")
        self.Distance_Label = QtWidgets.QLabel(self.PathUpdate_groupBox)
        self.Distance_Label.setGeometry(QtCore.QRect(610, 30, 61, 31))
        self.Distance_Label.setStyleSheet("border-color: rgba(255, 255, 255, 0);")
        self.Distance_Label.setObjectName("Distance_Label")
        self.PathDelete_Button = QtWidgets.QPushButton(self.PathUpdate_groupBox)
        self.PathDelete_Button.setGeometry(QtCore.QRect(800, 70, 121, 25))
        self.PathDelete_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}")
        self.PathDelete_Button.setObjectName("PathDelete_Button")
        self.PathUpdate_Button = QtWidgets.QPushButton(self.PathUpdate_groupBox)
        self.PathUpdate_Button.setGeometry(QtCore.QRect(650, 70, 121, 25))
        self.PathUpdate_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}")
        self.PathUpdate_Button.setObjectName("PathUpdate_Button")
        self.InputLength_TextEdit = QtWidgets.QPlainTextEdit(self.PathUpdate_groupBox)
        self.InputLength_TextEdit.setGeometry(QtCore.QRect(670, 30, 261, 31))
        self.InputLength_TextEdit.setObjectName("InputLength_TextEdit")
        self.Meter_Label = QtWidgets.QLabel(self.PathUpdate_groupBox)
        self.Meter_Label.setGeometry(QtCore.QRect(950, 30, 31, 31))
        self.Meter_Label.setStyleSheet("border-color: rgba(255, 255, 255, 0);")
        self.Meter_Label.setObjectName("Meter_Label")
        self.LogUpdate_groupBox = QtWidgets.QGroupBox(Dialog)
        self.LogUpdate_groupBox.setGeometry(QtCore.QRect(1070, 650, 201, 111))
        self.LogUpdate_groupBox.setStyleSheet("border:1px solid black")
        self.LogUpdate_groupBox.setObjectName("LogUpdate_groupBox")
        self.LogClear_Button = QtWidgets.QPushButton(self.LogUpdate_groupBox)
        self.LogClear_Button.setGeometry(QtCore.QRect(30, 40, 141, 41))
        self.LogClear_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}")
        self.LogClear_Button.setObjectName("LogClear_Button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.Attr_TableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.Attr_TableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Attr_TableWidget.verticalHeader().setVisible(False)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.AttrUpdateOrDel_groupBox.setTitle(_translate("Dialog", "景点信息管理"))
        self.InputAttrName_TextEdit.setPlaceholderText(_translate("Dialog", "请输入景点名称"))
        self.AttrSearch_Button.setText(_translate("Dialog", "查询"))
        item = self.Attr_TableWidget.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "1"))
        item = self.Attr_TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "编号"))
        item = self.Attr_TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "名称"))
        item = self.Attr_TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "横坐标"))
        item = self.Attr_TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "纵坐标"))
        item = self.Attr_TableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "简介"))
        item = self.Attr_TableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "介绍"))
        item = self.Attr_TableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "活动"))
        __sortingEnabled = self.Attr_TableWidget.isSortingEnabled()
        self.Attr_TableWidget.setSortingEnabled(False)
        self.Attr_TableWidget.setSortingEnabled(__sortingEnabled)
        self.AddName_plainTextEdit.setPlaceholderText(_translate("Dialog", "请输入景点名称"))
        self.AddX_plainTextEdit.setPlaceholderText(_translate("Dialog", "请输入横坐标"))
        self.AddY_plainTextEdit.setPlaceholderText(_translate("Dialog", "请输入纵坐标"))
        self.AddMiniIntro_plainTextEdit.setPlaceholderText(_translate("Dialog", "请输入景点简介"))
        self.AddIntro_plainTextEdit.setPlaceholderText(_translate("Dialog", "请输入景点介绍"))
        self.AddActive_plainTextEdit.setPlaceholderText(_translate("Dialog", "请输入景点活动"))
        self.Add_Button.setText(_translate("Dialog", "添加"))
        self.AttrUpdate_Button.setText(_translate("Dialog", "修改"))
        self.AttrDelete_Button.setText(_translate("Dialog", "删除"))
        self.PathUpdate_groupBox.setTitle(_translate("Dialog", "路径信息管理"))
        self.Destination_TextEdit.setPlaceholderText(_translate("Dialog", "请输入路径终点名称"))
        self.StartingPoint_TextEdit.setPlaceholderText(_translate("Dialog", "请输入路径起点名称"))
        self.PathSearch_Button.setText(_translate("Dialog", "查询"))
        self.To_Label.setText(_translate("Dialog", "至"))
        self.Distance_Label.setText(_translate("Dialog", "距离为"))
        self.PathDelete_Button.setText(_translate("Dialog", "删除"))
        self.PathUpdate_Button.setText(_translate("Dialog", "更新"))
        self.InputLength_TextEdit.setPlainText(_translate("Dialog", "0"))
        self.Meter_Label.setText(_translate("Dialog", "米"))
        self.LogUpdate_groupBox.setTitle(_translate("Dialog", "日志信息管理"))
        self.LogClear_Button.setText(_translate("Dialog", "清空所有日志"))
