# -*- coding: UTF-8 -*-
# editor: JiaYunSong
# Created by: PyQt5 UI code generator 5.15.0


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1301, 781)
        self.PathInf = QtWidgets.QGroupBox(Dialog)
        self.PathInf.setGeometry(QtCore.QRect(20, 20, 321, 171))
        self.PathInf.setStyleSheet("border:1px solid black")
        self.PathInf.setObjectName("PathInf")
        self.PosSelect = QtWidgets.QComboBox(self.PathInf)
        self.PosSelect.setGeometry(QtCore.QRect(110, 30, 171, 22))
        self.PosSelect.setStyleSheet("background-color: rgba(255, 255, 255, 255);")
        self.PosSelect.setObjectName("PosSelect")
        self.Path = QtWidgets.QWidget(self.PathInf)
        self.Path.setGeometry(QtCore.QRect(10, 59, 301, 101))
        self.Path.setStyleSheet("border:0px solid black\n"
"")
        self.Path.setObjectName("Path")
        self.label_3 = QtWidgets.QLabel(self.Path)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.label_3.setStyleSheet("border:0px solid black")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Path)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 71, 21))
        self.label_4.setStyleSheet("border:0px solid black")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Path)
        self.label_5.setGeometry(QtCore.QRect(230, 20, 21, 21))
        self.label_5.setStyleSheet("border:0px solid black")
        self.label_5.setObjectName("label_5")
        self.pathLength_Text = QtWidgets.QLabel(self.Path)
        self.pathLength_Text.setGeometry(QtCore.QRect(100, 20, 101, 21))
        self.pathLength_Text.setStyleSheet("border:0px solid black")
        self.pathLength_Text.setObjectName("pathLength_Text")
        self.pathClock_Text = QtWidgets.QLabel(self.Path)
        self.pathClock_Text.setGeometry(QtCore.QRect(100, 70, 101, 21))
        self.pathClock_Text.setStyleSheet("border:0px solid black")
        self.pathClock_Text.setObjectName("pathClock_Text")
        self.label_8 = QtWidgets.QLabel(self.Path)
        self.label_8.setGeometry(QtCore.QRect(230, 70, 41, 21))
        self.label_8.setStyleSheet("border:0px solid black")
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(self.PathInf)
        self.label.setGeometry(QtCore.QRect(21, 30, 71, 21))
        self.label.setStyleSheet("border:0px solid black")
        self.label.setObjectName("label")
        self.FunSelect = QtWidgets.QGroupBox(Dialog)
        self.FunSelect.setGeometry(QtCore.QRect(360, 20, 321, 361))
        self.FunSelect.setStyleSheet("border:1px solid black")
        self.FunSelect.setObjectName("FunSelect")
        self.ShortestPathSelect_Button = QtWidgets.QPushButton(self.FunSelect)
        self.ShortestPathSelect_Button.setGeometry(QtCore.QRect(60, 100, 201, 41))
        self.ShortestPathSelect_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.ShortestPathSelect_Button.setObjectName("ShortestPathSelect_Button")
        self.CirclePathSelect_Button = QtWidgets.QPushButton(self.FunSelect)
        self.CirclePathSelect_Button.setGeometry(QtCore.QRect(60, 40, 201, 41))
        self.CirclePathSelect_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}\n"
"background-color: rgba(255, 255, 255, 255);")
        self.CirclePathSelect_Button.setObjectName("CirclePathSelect_Button")
        self.KShortestPathSelect_Button = QtWidgets.QPushButton(self.FunSelect)
        self.KShortestPathSelect_Button.setGeometry(QtCore.QRect(60, 230, 201, 41))
        self.KShortestPathSelect_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.KShortestPathSelect_Button.setObjectName("KShortestPathSelect_Button")
        self.FuncDisSelect = QtWidgets.QSpinBox(self.FunSelect)
        self.FuncDisSelect.setGeometry(QtCore.QRect(140, 170, 121, 31))
        self.FuncDisSelect.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.FuncDisSelect.setMinimum(1)
        self.FuncDisSelect.setMaximum(10000)
        self.FuncDisSelect.setObjectName("FuncDisSelect")
        self.label_6 = QtWidgets.QLabel(self.FunSelect)
        self.label_6.setGeometry(QtCore.QRect(60, 170, 71, 31))
        self.label_6.setStyleSheet("border:0px solid black")
        self.label_6.setObjectName("label_6")
        self.DisShortPathSelect_Button = QtWidgets.QPushButton(self.FunSelect)
        self.DisShortPathSelect_Button.setGeometry(QtCore.QRect(60, 290, 201, 41))
        self.DisShortPathSelect_Button.setStyleSheet("QPushButton {background-color : #FFF;} \n"
"QPushButton:hover{background-color: #DDD;}\n"
"QPushButton:pressed {background-color: #00000000;}\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.DisShortPathSelect_Button.setObjectName("DisShortPathSelect_Button")

        self.HotSight = QtWidgets.QGroupBox(Dialog)
        self.HotSight.setGeometry(QtCore.QRect(360, 400, 321, 361))
        self.HotSight.setStyleSheet("border:1px solid black")
        self.HotSight.setObjectName("HotSight")
        self.HotSight2 = QtWidgets.QWidget(self.HotSight)
        self.HotSight2.setGeometry(QtCore.QRect(20, 140, 291, 101))
        self.HotSight2.setToolTip("")
        self.HotSight2.setStyleSheet("border:0px solid black")
        self.HotSight2.setObjectName("HotSight2")
        self.HotSight2_bg = QtWidgets.QLabel(self.HotSight2)
        self.HotSight2_bg.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.HotSight2_bg.setStyleSheet("border:0px solid black;")
        self.HotSight2_bg.setObjectName("HotSight2_bg")
        self.HotSight2_Name = QtWidgets.QLabel(self.HotSight2)
        self.HotSight2_Name.setGeometry(QtCore.QRect(110, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.HotSight2_Name.setFont(font)
        self.HotSight2_Name.setStyleSheet("border:0px solid black")
        self.HotSight2_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.HotSight2_Name.setObjectName("HotSight2_Name")
        self.HotSight2_Text = QtWidgets.QLabel(self.HotSight2)
        self.HotSight2_Text.setGeometry(QtCore.QRect(110, 40, 171, 51))
        self.HotSight2_Text.setStyleSheet("border:0px solid black")
        self.HotSight2_Text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.HotSight2_Text.setObjectName("HotSight2_Text")
        self.HotSight2_JPG = QtWidgets.QLabel(self.HotSight2)
        self.HotSight2_JPG.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.HotSight2_JPG.setStyleSheet("border:0px solid black")
        self.HotSight2_JPG.setObjectName("HotSight2_JPG")
        self.HotSight2_Pushbutton = QtWidgets.QPushButton(self.HotSight2)
        self.HotSight2_Pushbutton.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.HotSight2_Pushbutton.setText("")
        self.HotSight2_Pushbutton.setObjectName("HotSight2_Pushbutton")
        self.HotSight3 = QtWidgets.QWidget(self.HotSight)
        self.HotSight3.setGeometry(QtCore.QRect(20, 250, 291, 101))
        self.HotSight3.setToolTip("")
        self.HotSight3.setStyleSheet("border:0px solid black")
        self.HotSight3.setObjectName("HotSight3")
        self.HotSight3_bg = QtWidgets.QLabel(self.HotSight3)
        self.HotSight3_bg.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.HotSight3_bg.setStyleSheet("border:0px solid black;")
        self.HotSight3_bg.setObjectName("HotSight3_bg")
        self.HotSight3_JPG = QtWidgets.QLabel(self.HotSight3)
        self.HotSight3_JPG.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.HotSight3_JPG.setStyleSheet("border:0px solid black")
        self.HotSight3_JPG.setObjectName("HotSight3_JPG")
        self.HotSight3_Text = QtWidgets.QLabel(self.HotSight3)
        self.HotSight3_Text.setGeometry(QtCore.QRect(110, 40, 171, 51))
        self.HotSight3_Text.setStyleSheet("border:0px solid black")
        self.HotSight3_Text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.HotSight3_Text.setObjectName("HotSight3_Text")
        self.HotSight3_Name = QtWidgets.QLabel(self.HotSight3)
        self.HotSight3_Name.setGeometry(QtCore.QRect(110, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.HotSight3_Name.setFont(font)
        self.HotSight3_Name.setStyleSheet("border:0px solid black")
        self.HotSight3_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.HotSight3_Name.setObjectName("HotSight3_Name")
        self.HotSight3_Pushbutton = QtWidgets.QPushButton(self.HotSight3)
        self.HotSight3_Pushbutton.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.HotSight3_Pushbutton.setText("")
        self.HotSight3_Pushbutton.setObjectName("HotSight3_Pushbutton")
        self.HotSight1 = QtWidgets.QWidget(self.HotSight)
        self.HotSight1.setGeometry(QtCore.QRect(20, 30, 291, 101))
        self.HotSight1.setStyleSheet("border:0px solid black")
        self.HotSight1.setObjectName("HotSight1")
        self.HotSight1_bg = QtWidgets.QLabel(self.HotSight1)
        self.HotSight1_bg.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.HotSight1_bg.setStyleSheet("border:0px solid black;")
        self.HotSight1_bg.setObjectName("HotSight1_bg")
        self.HotSight1_JPG = QtWidgets.QLabel(self.HotSight1)
        self.HotSight1_JPG.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.HotSight1_JPG.setStyleSheet("border:0px solid black")
        self.HotSight1_JPG.setObjectName("HotSight1_JPG")
        self.HotSight1_Name = QtWidgets.QLabel(self.HotSight1)
        self.HotSight1_Name.setGeometry(QtCore.QRect(110, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.HotSight1_Name.setFont(font)
        self.HotSight1_Name.setStyleSheet("border:0px solid black")
        self.HotSight1_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.HotSight1_Name.setObjectName("HotSight1_Name")
        self.HotSight1_Text = QtWidgets.QLabel(self.HotSight1)
        self.HotSight1_Text.setGeometry(QtCore.QRect(110, 40, 171, 51))
        self.HotSight1_Text.setStyleSheet("border:0px solid black")
        self.HotSight1_Text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.HotSight1_Text.setObjectName("HotSight1_Text")
        self.HotSight1_Pushbutton = QtWidgets.QPushButton(self.HotSight1)
        self.HotSight1_Pushbutton.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.HotSight1_Pushbutton.setText("")
        self.HotSight1_Pushbutton.setObjectName("HotSight1_Pushbutton")
        self.NearSight = QtWidgets.QGroupBox(Dialog)
        self.NearSight.setGeometry(QtCore.QRect(20, 210, 321, 551))
        self.NearSight.setStyleSheet("border:1px solid black;")
        self.NearSight.setObjectName("NearSight")
        self.Search_Button = QtWidgets.QPushButton(self.NearSight)
        self.Search_Button.setGeometry(QtCore.QRect(242, 30, 61, 31))
        self.Search_Button.setStyleSheet("QPushButton {background-color : #FFF;border:1px solid black;} \n"
"QPushButton:hover{background-color: #DDD;border:1px solid black;}\n"
"QPushButton:pressed {background-color: #00000000;border:1px solid black;}\n"
"background-color: rgba(255, 255, 255, 255);")
        self.Search_Button.setObjectName("Search_Button")
        self.NearSight2 = QtWidgets.QWidget(self.NearSight)
        self.NearSight2.setGeometry(QtCore.QRect(20, 200, 291, 101))
        self.NearSight2.setToolTip("")
        self.NearSight2.setStyleSheet("border:0px solid black")
        self.NearSight2.setObjectName("NearSight2")
        self.NearSight2_bg = QtWidgets.QLabel(self.NearSight2)
        self.NearSight2_bg.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.NearSight2_bg.setStyleSheet("border:0px solid black;")
        self.NearSight2_bg.setObjectName("NearSight2_bg")
        self.NearSight2_JPG = QtWidgets.QLabel(self.NearSight2)
        self.NearSight2_JPG.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.NearSight2_JPG.setStyleSheet("border:0px solid black")
        self.NearSight2_JPG.setObjectName("NearSight2_JPG")
        self.NearSight2_Name = QtWidgets.QLabel(self.NearSight2)
        self.NearSight2_Name.setGeometry(QtCore.QRect(110, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.NearSight2_Name.setFont(font)
        self.NearSight2_Name.setStyleSheet("border:0px solid black")
        self.NearSight2_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.NearSight2_Name.setObjectName("NearSight2_Name")
        self.NearSight2_Text = QtWidgets.QLabel(self.NearSight2)
        self.NearSight2_Text.setGeometry(QtCore.QRect(110, 40, 171, 51))
        self.NearSight2_Text.setStyleSheet("border:0px solid black")
        self.NearSight2_Text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.NearSight2_Text.setObjectName("NearSight2_Text")
        self.NearSight2_Pushbutton = QtWidgets.QPushButton(self.NearSight2)
        self.NearSight2_Pushbutton.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.NearSight2_Pushbutton.setText("")
        self.NearSight2_Pushbutton.setObjectName("NearSight2_Pushbutton")
        self.DisSelect = QtWidgets.QSpinBox(self.NearSight)
        self.DisSelect.setGeometry(QtCore.QRect(95, 31, 131, 31))
        self.DisSelect.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.DisSelect.setMaximum(1000)
        self.DisSelect.setObjectName("DisSelect")
        self.label_2 = QtWidgets.QLabel(self.NearSight)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 71, 31))
        self.label_2.setStyleSheet("border:0px solid black")
        self.label_2.setObjectName("label_2")
        self.NearSight3 = QtWidgets.QWidget(self.NearSight)
        self.NearSight3.setGeometry(QtCore.QRect(20, 320, 291, 101))
        self.NearSight3.setToolTip("")
        self.NearSight3.setStyleSheet("border:0px solid black")
        self.NearSight3.setObjectName("NearSight3")
        self.NearSight3_bg = QtWidgets.QLabel(self.NearSight3)
        self.NearSight3_bg.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.NearSight3_bg.setStyleSheet("border:0px solid black;")
        self.NearSight3_bg.setObjectName("NearSight3_bg")
        self.NearSight3_JPG = QtWidgets.QLabel(self.NearSight3)
        self.NearSight3_JPG.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.NearSight3_JPG.setStyleSheet("border:0px solid black")
        self.NearSight3_JPG.setObjectName("NearSight3_JPG")
        self.NearSight3_Name = QtWidgets.QLabel(self.NearSight3)
        self.NearSight3_Name.setGeometry(QtCore.QRect(110, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.NearSight3_Name.setFont(font)
        self.NearSight3_Name.setStyleSheet("border:0px solid black")
        self.NearSight3_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.NearSight3_Name.setObjectName("NearSight3_Name")
        self.NearSight3_Text = QtWidgets.QLabel(self.NearSight3)
        self.NearSight3_Text.setGeometry(QtCore.QRect(110, 40, 171, 51))
        self.NearSight3_Text.setStyleSheet("border:0px solid black")
        self.NearSight3_Text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.NearSight3_Text.setObjectName("NearSight3_Text")
        self.NearSight3_Pushbutton = QtWidgets.QPushButton(self.NearSight3)
        self.NearSight3_Pushbutton.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.NearSight3_Pushbutton.setText("")
        self.NearSight3_Pushbutton.setObjectName("NearSight3_Pushbutton")
        self.NearSight4 = QtWidgets.QWidget(self.NearSight)
        self.NearSight4.setGeometry(QtCore.QRect(20, 440, 291, 101))
        self.NearSight4.setToolTip("")
        self.NearSight4.setStyleSheet("border:0px solid black")
        self.NearSight4.setObjectName("NearSight4")
        self.NearSight4_bg = QtWidgets.QLabel(self.NearSight4)
        self.NearSight4_bg.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.NearSight4_bg.setStyleSheet("border:0px solid black;")
        self.NearSight4_bg.setObjectName("NearSight4_bg")
        self.NearSight4_Text = QtWidgets.QLabel(self.NearSight4)
        self.NearSight4_Text.setGeometry(QtCore.QRect(110, 40, 171, 51))
        self.NearSight4_Text.setStyleSheet("border:0px solid black")
        self.NearSight4_Text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.NearSight4_Text.setObjectName("NearSight4_Text")
        self.NearSight4_JPG = QtWidgets.QLabel(self.NearSight4)
        self.NearSight4_JPG.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.NearSight4_JPG.setStyleSheet("border:0px solid black")
        self.NearSight4_JPG.setObjectName("NearSight4_JPG")
        self.NearSight4_Name = QtWidgets.QLabel(self.NearSight4)
        self.NearSight4_Name.setGeometry(QtCore.QRect(110, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.NearSight4_Name.setFont(font)
        self.NearSight4_Name.setStyleSheet("border:0px solid black")
        self.NearSight4_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.NearSight4_Name.setObjectName("NearSight4_Name")
        self.NearSight4_Pushbutton = QtWidgets.QPushButton(self.NearSight4)
        self.NearSight4_Pushbutton.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.NearSight4_Pushbutton.setText("")
        self.NearSight4_Pushbutton.setObjectName("NearSight4_Pushbutton")
        self.NearSight1 = QtWidgets.QWidget(self.NearSight)
        self.NearSight1.setGeometry(QtCore.QRect(20, 80, 291, 101))
        self.NearSight1.setStyleSheet("border:0px solid black")
        self.NearSight1.setObjectName("NearSight1")
        self.NearSight1_bg = QtWidgets.QLabel(self.NearSight1)
        self.NearSight1_bg.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.NearSight1_bg.setStyleSheet("border:0px solid black;")
        self.NearSight1_bg.setObjectName("NearSight1_bg")
        self.NearSight1_Text = QtWidgets.QLabel(self.NearSight1)
        self.NearSight1_Text.setGeometry(QtCore.QRect(110, 40, 171, 51))
        self.NearSight1_Text.setStyleSheet("border:0px solid black")
        self.NearSight1_Text.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.NearSight1_Text.setObjectName("NearSight1_Text")
        self.NearSight1_JPG = QtWidgets.QLabel(self.NearSight1)
        self.NearSight1_JPG.setGeometry(QtCore.QRect(10, 10, 91, 81))
        self.NearSight1_JPG.setStyleSheet("border:0px solid black")
        self.NearSight1_JPG.setObjectName("NearSight1_JPG")
        self.NearSight1_Name = QtWidgets.QLabel(self.NearSight1)
        self.NearSight1_Name.setGeometry(QtCore.QRect(110, 10, 171, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(12)
        self.NearSight1_Name.setFont(font)
        self.NearSight1_Name.setStyleSheet("border:0px solid black")
        self.NearSight1_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.NearSight1_Name.setObjectName("NearSight1_Name")
        self.NearSight1_Pushbutton = QtWidgets.QPushButton(self.NearSight1)
        self.NearSight1_Pushbutton.setGeometry(QtCore.QRect(0, 0, 291, 101))
        self.NearSight1_Pushbutton.setText("")
        self.NearSight1_Pushbutton.setObjectName("NearSight1_Pushbutton")
        self.Map = QtWidgets.QWidget(Dialog)
        self.Map.setGeometry(QtCore.QRect(699, 19, 591, 741))
        self.Map.setStyleSheet("")
        self.Map.setObjectName("Map")

        self.HotSight1_JPG.setScaledContents(True)
        self.HotSight2_JPG.setScaledContents(True)
        self.HotSight3_JPG.setScaledContents(True)
        self.NearSight1_JPG.setScaledContents(True)
        self.NearSight2_JPG.setScaledContents(True)
        self.NearSight3_JPG.setScaledContents(True)
        self.NearSight4_JPG.setScaledContents(True)

        self.HotSight1_Text.setWordWrap(True)
        self.HotSight2_Text.setWordWrap(True)
        self.HotSight3_Text.setWordWrap(True)
        self.NearSight1_Text.setWordWrap(True)
        self.NearSight2_Text.setWordWrap(True)
        self.NearSight3_Text.setWordWrap(True)
        self.NearSight4_Text.setWordWrap(True)

        self.painter = QtGui.QPainter(self.Map)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.PathInf.setTitle(_translate("Dialog", "路径信息"))
        self.label_3.setText(_translate("Dialog", "最短距离"))
        self.label_4.setText(_translate("Dialog", "预计耗时"))
        self.label_5.setText(_translate("Dialog", "米"))
        self.pathLength_Text.setText(_translate("Dialog", "0"))
        self.pathClock_Text.setText(_translate("Dialog", "0"))
        self.label_8.setText(_translate("Dialog", "分钟"))
        self.label.setText(_translate("Dialog", "当前位置"))
        self.FunSelect.setTitle(_translate("Dialog", "功能选择"))
        self.ShortestPathSelect_Button.setText(_translate("Dialog", "最短路径查询"))
        self.CirclePathSelect_Button.setText(_translate("Dialog", "环形路线查询"))
        self.KShortestPathSelect_Button.setText(_translate("Dialog", "k短路径查询"))
        self.DisShortPathSelect_Button.setText(_translate("Dialog", "适宜距离内路径查询"))
        self.label_6.setText(_translate("Dialog", "路径条数："))
        self.HotSight.setTitle(_translate("Dialog", "热门景点推荐"))
        self.HotSight2_Name.setText(_translate("Dialog", "景点名称"))
        self.HotSight2_Text.setText(_translate("Dialog", "景点简介"))
        self.HotSight3_Text.setText(_translate("Dialog", "景点简介"))
        self.HotSight3_Name.setText(_translate("Dialog", "景点名称"))
        self.HotSight1_Name.setText(_translate("Dialog", "景点名称"))
        self.HotSight1_Text.setText(_translate("Dialog", "景点简介"))
        self.NearSight.setTitle(_translate("Dialog", "附近景点推荐"))
        self.Search_Button.setText(_translate("Dialog", "搜索"))
        self.NearSight2_Name.setText(_translate("Dialog", "景点名称"))
        self.NearSight2_Text.setText(_translate("Dialog", "景点简介"))
        self.label_2.setText(_translate("Dialog", "范围选择"))
        self.NearSight3_Name.setText(_translate("Dialog", "景点名称"))
        self.NearSight3_Text.setText(_translate("Dialog", "景点简介"))
        self.NearSight4_Text.setText(_translate("Dialog", "景点简介"))
        self.NearSight4_Name.setText(_translate("Dialog", "景点名称"))
        self.NearSight1_Text.setText(_translate("Dialog", "景点简介"))
        self.NearSight1_Name.setText(_translate("Dialog", "景点名称"))
